### ISSUE TITLE
Linux deployment to AppImage

### ISSUE THREAD

**Issue by d1vanov** [d1vanov/quentier#118]
Finally the time has come to do this.

First need to try [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) tool. It appears to be not really production ready but still the major player in the field. If that doesn't work, can try some forks/derivatives:

1. [linuxdeploy](https://github.com/Ribtoks/linuxdeploy) - written in Go
2. [pure shell version](https://github.com/webcamoid/webcamoid/blob/master/ports/deploy/linux/linuxdeploy.sh)

**Comment by vitaly-zdanevich** [comment]
So, what about appImage?

**Comment by d1vanov** [comment]
What about it? It's done long time ago, AppImage packages are automatically uploaded to continuous releases.

**Comment by vitaly-zdanevich** [comment]
hmm but not in Releases
![image](https://github.com/d1vanov/quentier/assets/3514015/ef245faf-e245-4905-b3d3-fbb81c41d1d2)

**Comment by d1vanov** [comment]
Your screen is packages, not releases
