### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [d1vanov/quentier#146]
```
libstdc++.so.6: version `GLIBCXX_3.4.20' not found
```

Please see
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

References:
https://github.com/AppImage/appimage.github.io/pull/210

**Comment by d1vanov** [comment]
Thank you for noticing this, I haven't yed had the chance to test the built AppImages myself.
Would buildig with gcc 4.8 shipped with Ubuntu 14.04 help to overcome this problem?

**Comment by probonopd** [comment]
Yes, building with the gcc that comes with Ubuntu 14.04 would be a way to overcome this problem.

**Comment by d1vanov** [comment]
Fixed via [46376ce](https://github.com/d1vanov/quentier/commit/46376ce509d559152538a9bee74bda1fd6bf7024) in branches [master](https://github.com/d1vanov/quentier/commit/master) and [development](https://github.com/d1vanov/quentier/commit/development).

**Comment by probonopd** [comment]
Thank you very much. Added to the AppImageHub central repository of available AppImages.
