### ISSUE TITLE
Make it possible to disable the display of thumbnails for particular notes within the notes list view

### ISSUE THREAD

**Issue by d1vanov** [d1vanov/quentier#164]
Thumbnails are downloaded from Evernote servers for notes containing attachments as a separate sync step. The thumbnails are always downloaded as images of fixed size - 300x300. Sometimes the image attached to the note from which Evernote generated a thumbnail is actually smaller than this size. It doesn't look very nice:
![notverynicethumbnail](https://user-images.githubusercontent.com/2050562/35548554-3ea70198-0591-11e8-9095-d8cdd6a0c761.png)
So it would be handy to have a way to right-click on this note and choose "Don't show thumbnail for this note" to permanently prevent the thumbnail display for this particular note. In fact, within the context menu we could have a nested menu: "Don't show thumbnail" -> "For this note"; "For all notes". The latter option would just trigger switching off the display of note thumbnails for all notes. Currently such option is accessible only via "Preferences" dialog. When the thumbnail is disabled for some individual note, another context menu item should be shown: "Show thumbnail for this note".

Implementation-wise, I think there shouldn't be many individual notes for which one might wish to disable the thumbnails display so it seems ok to just store the list of note local uids within [ApplicationSettings](https://github.com/d1vanov/libquentier/blob/master/headers/quentier/utility/ApplicationSettings.h) (augmenting [QSettings](http://doc.qt.io/qt-5/qsettings.html)). The list would be filled by `NoteListView` (as it receives and processed context menu events) and used by `NoteItemDelegate` (as it is the class performing the actual rendering of note items) to decide whether the thumbnail should be displayed for particular note or not.

**Comment by robert7** [comment]
ok. I take this also as starter :)

**Comment by d1vanov** [comment]
Closed via #200 in development branch.
