### ISSUE TITLE
Use the default theme and icons on Plasma

### ISSUE THREAD

**Issue by mateushonorato** [d1vanov/quentier#166]
![screenshot_20180131_104055](https://user-images.githubusercontent.com/16072496/35623961-96b9b93c-0674-11e8-9417-ff44f63a280a.png)

I think this theme looks really ugly and outdated. A good solution, at least on the Plasma desktop, would be to use the default theme (breeze) and icons, so it could look more cohesive with the desktop.

**Comment by d1vanov** [comment]
The icons actually should be picked from the current desktop theme if it's found. If it's not found, the fallback is done on Oxygen icon set. Are you using the AppImage downloaded from the releases page? If so, it might be the problem connected to the AppImage that it's unable to detect the native icon theme. You can check it as follows: go to "View" menu -> "Look and feel" -> "Icons". If you see "Native" option there and it's not chosen, try to choose it. If there's no "Native" option there, it must be somehow connected to the AppImage packaging of the app.

Besides icons, currently there's a minimal ability to customize the color of the panels - what you see is the default but you can change it by playing with options in "View" -> "Look and feel" -> "Panels". That's not much, granted but that's what's implemented by now. In future I plan to add more UI customization options, in particular I created #161 to allow for easier customization of icon set used by the app.

**Comment by d1vanov** [comment]
It looks like some extra efforts might be required to get the AppImage packaged Quentier use the proper icons and stuff, [this thread](https://discourse.appimage.org/t/how-to-integrate-an-appimage-into-plasma-kde/218) for reference. Personally, I consider Quentier AppImage package a short term hack solution before I set up repositories at launchpad and at OpenSuse build factory for more native versions for popular distributions. So not sure if it's worth to invest effort into improving the AppImage.

**Comment by polarathene** [comment]
Would it be possible to package the KDE Breeze theme/icons in the AppImage? I think most would agree that it would give a more modern/polished look and should carry over across to other DE/OS. On Windows for example I've found other Qt apps have similar outdated look, QOwnNotes(Very similar to this, minus Evernote integration) and qBittorrent exhibit this. 

I understand some may not like the flat/modern type of UI design, but my bet is on the majority preferring the polished/consistent style that Breeze offers. If you do package it, and it's possible to switch, it may be of interest to include Breeze Light and Dark themes.

I presently use QOwnNotes, if I see a native package in Arch Linux AUR pop up later, I'll give Quentier a try. For now the current aesthetics would affect the UX for me, the features and functionality sound great though!

**Comment by d1vanov** [comment]
I could indeed just package and distribute Breeze icon theme along with the application itself but I don't really like this option much - after that I'd be asked to add one more icon theme and one more etc so I'll end up redistributing a whole heck of stuff. Instead, at least for the Linux world, the better option seems to be having natively packaged app for each distro. Well, at least for popular ones worth spending the effort on.

I understand the UX issues with AppImage, I hoped it'd be good enough in integrating into the desktop but it seems it's not. So I think I'll just prioritize native packaging over other things I was going to do in near future. If anyone could help with that, it would be great, packaging for multiple distros would take much more time for me alone.

**Comment by polarathene** [comment]
> but I don't really like this option much - after that I'd be asked to add one more icon theme and one more etc so I'll end up redistributing a whole heck of stuff.

That'd be completely up to you. I and other users are going to be put off by the look of the application UI, I've had people see the Breeze screenshots of QOwnNotes but when seeing it without the Breeze theme and whatever the default fallback is that Windows or other DE/OS provide is, it doesn't look as enticing to them to use. Breeze is well done, if you don't want to include it that's fine, if possible to support a way for a user to add/apply the theme via settings, that could be just as good? I imagine that might be more work to support(if possible?).

The integration according to other users who have tried is pretty spot on, it's jsut a lack of using the system theme that I've found to be a problem with AppImage. I think this is better situation with Flatpak, but it requires whatever theme to be applied to exist in a Flatpak form(this should be fine with Breeze afaik, or will be in future). Flatpak may be worth giving a shot to avoid packaging for many distros if possible(I raised an issue for it), but I can understand just preferring to support the popular distros instead.

Ubuntu is a given, Arch Linux(and it's related distros like Antergos and Manjaro) would be another via AUR, openSUSE perhaps too :)

I've not personally packaged any app for Linux myself, but I'm aware that here is a project designed to make packaging for multiple distros easier and automated. Unfortunately I don't recall the name off the top of my head.

**Comment by d1vanov** [comment]
> I and other users are going to be put off by the look of the application UI

I can perfectly understand that. My original idea was for Quentier on Linux to use whatever icons/widgets/colors etc provided by the theme. I've added two fallback options - Oxygen and Tango - primarily for Windows and Mac where there's simply no such a thing as the native icon theme.

> if possible to support a way for a user to add/apply the theme via settings, that could be just as good?

Yes, it would be nice to support a way to "assign" the set of icons for the application - for that I created #161. 

About the distros to support, I currently think of

1. Debian, Ubuntu and their derivatives
2. Fedora and its relatives from the RPM world
3. Arch and its derivatives

For others the recommendation would be to either use the AppImage or compile from source manually or, even better, not just compile but create the package for the distro, whatever it is - emerge for Gentoo, for example.

> I've not personally packaged any app for Linux myself, but I'm aware that here is a project designed to make packaging for multiple distros easier and automated. Unfortunately I don't recall the name off the top of my head.
It's called [OpenSUSE build service](https://build.opensuse.org/), I just created #168 to track the progress on that.

**Comment by d1vanov** [comment]
I'm closing this one because the missing theming problem is due to an AppImage limitation which I won't be attempting to workaround. Instead I'll consider preparing native packages for major Linux distros which should play nicer with the DE theme: #168 and #158.
