### ISSUE TITLE
Make use of OpenSUSE build service to build packages for several Linux distros

### ISSUE THREAD

**Issue by d1vanov** [d1vanov/quentier#168]
See the discussion in #166, the intention is to try and use [OpenSUSE build service](https://build.opensuse.org) for the creation of Quentier packages (and its relevant dependencies' packages) for several Linux distros.

**Comment by eclipseo** [comment]
I somewhat maintain a Quentier on Fedora build service, COPR:

https://copr.fedorainfracloud.org/coprs/eclipseo/quentier/

I don't know about OpenSuse, but you can find my SPEC files here:

- https://github.com/eclipseo/packaging/blob/master/qevercloud.spec
- https://github.com/eclipseo/packaging/blob/master/libquentier.spec
- https://github.com/eclipseo/packaging/blob/master/quentier.spec

**Comment by d1vanov** [comment]
Wow! That's freaking awesome, thank you very much! I'll definitely look into your SPEC files, also will add the info about your repo to README when I have some free time.

**Comment by d1vanov** [comment]
Thanks to @eclipseo's specs, I have successfully set up builds of Quentier's master branch for Fedora 26 and 27 at OpenSUSE build factory, the "subproject" (that's the term used by OpenSUSE build service) is [here](https://build.opensuse.org/package/show/home:d1vanov:quentier-master). It's not yet ready for casual usage as supporting other RPM-based distros would require some mumbo-jumbo with specs as several details of it are distro-specific. Currently I'm struggling with OpenSUSE Tumbleweed and Leap 42. Will also probably look into CentOS and then perhaps will try to set up things for Arch Linux.

**Comment by d1vanov** [comment]
A couple of useful links:

- [How to write one spec to work for several RPM-based distros](https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto)
- [Some differences between several RPM spec "dialects"](https://wiki.mageia.org/en/RPM_spec_lingo_across_distributions)

**Comment by d1vanov** [comment]
Set up repositories for Fedora 26, Fedora 27, OpenSUSE Tumbleweed, OpenSUSE Leap 15.0, Debian 9.0 and got stuck with Arch Linux packaging due to what seems to be a [bug](https://lists.opensuse.org/opensuse-buildservice/2018-03/msg00035.html) of OpenSUSE build service.

**Comment by d1vanov** [comment]
I believe this one can finally be considered finished. I found a way to sort out the issue with Arch Linux at OBS only had to build libquentier with QtWebKit instead of QtWebEngine since it caused some dependency issue which I had no idea how to resolve. But anyway, native binary packages built from both master and development branches are now available for the following distributions:

- Fedora 26
- Fedora 27
- OpenSUSE Leap 42.3
- OpenSUSE Leap 15.0
- OpenSUSE Tumbleweed
- Debian 9.0
- Arch Linux

Before that PPA repositories for different flavours of Ubuntu were set up (#158). For each distro there are packages built from both master and development branches + I even managed to figure out how to set up automatic triggering of builds on git push - it is simple for a single branch but not so simple for two or more branches. The installation instructions for all of this stuff are written down in README.md.

Will perhaps look into packaging with Flatpak now (#167).
