### ISSUE TITLE
Texts of notes display incorrectly.

### ISSUE THREAD

**Issue by forest71** [d1vanov/quentier#179]
I imported enex file from evernote to quentier but all texts of imported notes looks like this: http://prntscr.com/k4fw49

I noticed it happens only with texts in russian language.

How to fix this problem?

**Comment by forest71** [comment]
Can't provide enex file right now, but you can reproduce this bug if you create a note in evernote with russian text, then export it to enex file and open it in Quentier .

Version of Quentier is 0.4.0 (Qt 5.10.1)
Platform: Windows
Setup file was downloaded from here: https://github.com/d1vanov/quentier
Qt 5.10 64 bit installer

**Comment by d1vanov** [comment]
Thanks for the info, will try to look into this. I guess it is somehow connected with UTF-16 being the default encoding on Windows.

**Comment by forest71** [comment]
Thanks, will wait for answer.

**Comment by forest71** [comment]
Ok, got it.

**Comment by d1vanov** [comment]
The build containing the fix is available now and can be downloaded from [here](https://ci.appveyor.com/project/d1vanov/quentier/build/job/08qxn7g9qweq5523/artifacts). @forest71, if you wish, you can try this build and see if it fixes your issue. Unfortunately, the already imported notes would not be fixed but the newly imported ones should be displayed properly. I still haven't tested it myself yet.

There are two downloads at the link:

1. `SetupQuentier<...>.exe` is the installer like the one you downloaded originally, it would replace the version you have installed now.
2. `Quentier-windows<...>.zip` is the zip archive containing Quentier executable, libraries and other needed stuff. You can unzip it anywhere and run without installing for testing purposes.

**Comment by forest71** [comment]
It worked. Now all texts display correctly, thanks.

1. Where Quentier keeps imported files?
Just in case I deleted previous version and installed Quentier from zip archive. When I opened this zip version all previous imported notes were still there.

2. When you update Quentier can you also upload portable version (just like Quentier from that archive)? It is very handy.

**Comment by d1vanov** [comment]
Great, thanks for verifying! Merged the fix to master and development branches, updated downloads will appear on releases page shortly.

1. Quentier stores all notes, imported or synchronized or manually typed in a local storage database. All persistent storage of Quentier including the database is located in a separate folder, not near the executable. In case of Windows the folder where Quentier's persistent storage is located is `C:\Users\%USERNAME%\AppData\Roaming\Quentier`. So if you want to wipe all your storage out, you need to remove that folder. Alternatively, in your case you could delete the notes you imported previously: in case of local account permanent deletion is possible, in case of Evernote account you can't actually delete the note permanently via Quentier (Evernote disallows third party apps to do that) but you can mark it as deleted which would make it disappear from your notes list and appear within the deleted notes list. If that latter one is not displayed in the bottom of the left side panel of the app, toggle its display via "View" -> "Side panel" -> "Show deleted notes" menu entry. The notes marked as deleted can be restored from Quentier or Evernote and they can be deleted permanently but only via the official Evernote client or web version of Evernote.
2. Yes, I guess it is possible to upload portable version to the releases page. I created #181 to do it carefully.

**Comment by forest71** [comment]
Understood, thanks.
There is something else.

I found several files in account folder:
.sqlite
.sqlite-shm
.sqlite-wal
folder "NoteEditorPage"

1. If I understand correctly, all notes (as well as imported) stored in .sqlite file, right?

2. What is the purpose of "NoteEditorPage" folder?

3. Is it possible to do so that all notes will be stored in one folder with Quentier itself? 
Situation for example: if you want to move portable version of Quentier to flash drive, you need to move only one folder (that include Quentier and it's databases) instead of two (folder with Quentier and folder with it's databases).

**Comment by d1vanov** [comment]
1. Yes, exactly. The two other sqlite files are just auxiliary ones managed by SQLite database itself.
2. This folder contains some auxiliary files used by the note editor. It is merely an implementation detail in fact - the note editor is implemented as a web page and it needs a `.html` file to display the note + image files for stuff like note attachments + some other stuff.
3. Yes, it is possible to change the storage folder, for that it's enough to run Quentier from command line with `--storageDir <path>` argument. On Windows you can put this argument into the properties of the label via which you start Quentier.

**Comment by d1vanov** [comment]
The information about the storage folder is actually explained in the beginning of [this article](https://github.com/d1vanov/quentier/wiki/Brief-overview-of-Quentier-features) about Quentier features. Given your question I conclude you haven't read it yet, so I encourage you to do so :smiley:

**Comment by forest71** [comment]
Thanks, will do.
