### ISSUE TITLE
The Preference dialog should be modal

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#189]
..else you can open many copies of the dialog. If happened to me like that: I wanted to open Preferences. I selected the menu option, but nothing happened, I repeated few times - nothing happens.
Then I noticed that the dialog is open on my second screen - in 5 copies..
![screen_20180719_04](https://user-images.githubusercontent.com/1135218/42963493-a89d2aa8-8b94-11e8-9b79-95dd9f7aad5e.png)

Maybe check if the position of the dialog can be influences someway, becasue its weited, that it open on other screen then die App itself is open (but this isn't so critical). If the dialog will be modal, then it will be easier to notice that its on the other screen.

Further I think it would be better to move Preferences in "Edit" menu. This is convention and users expect it to be there.

And maybe rename menu option from "Settings" to "Preferences" (again convention) and the dialog itself is called "Preferences" (or at least have same name for dialog & menu option).

I used development branch with Qt 5.5.1 to reproduce.

**Comment by d1vanov** [comment]
A funny one :smiley: 

Well, preferences dialog seems to already be modal:
```
void MainWindow::onShowSettingsDialogAction()                                                                               
{                                                                                                                           
    QNDEBUG(QStringLiteral("MainWindow::onShowSettingsDialogAction"));                                                      
                                                                                                                            
    QList<QMenu*> menus = m_pUI->menuBar->findChildren<QMenu*>();                                                           
    ActionsInfo actionsInfo(menus);                                                                                         
                                                                                                                            
    QScopedPointer<PreferencesDialog> pPreferencesDialog(new PreferencesDialog(*m_pAccountManager,                          
                                                                               m_shortcutManager,                           
                                                                               *m_pSystemTrayIconManager,                   
                                                                               actionsInfo, this));                         
    pPreferencesDialog->setWindowModality(Qt::WindowModal);
    <...>
}
```
but it doesn't seem to help. I think we could perhaps do the following in the beginning of this method to prevent many dialogs: try to find the child of `MainWindow` of `PreferencesDialog` type. If we find one, this dialog must already be open so we won't open a second one.

About where this dialog is to be shown: there's `MainWindow::centerWidget` method which can be used to put the center of any widget into the center point of main window thus making the widget appear on top of the main window and right in the middle of it. Perhaps it should be used for this dialog as well.

> Further I think it would be better to move Preferences in "Edit" menu. This is convention and users expect it to be there.
And maybe rename menu option from "Settings" to "Preferences" (again convention) and the dialog itself is called "Preferences" (or at least have same name for dialog & menu option).

Agree with both of these points.

**Comment by d1vanov** [comment]
Should be solved now in development, however, I wasn't actually able to reproduce the original issue: for me window modality seems to work properly i.e. if I have opened preferences dialog once, I can't do anything with Quentier's main window before I close the dialog i.e. I simply can't access the main window's menu which would allow me to open preferences dialog again. Nevertheless, I added protection againts opening this dialog for the second and subsequent times which I mentioned above. Also tried to make this dialog to appear centered with respect to the main window. Aside of that, I moved the menu entry under "Edit" menu and remaned it to "Preferences" as you suggested. Closing this one as it should be working properly now, please reopen if it still doesn't work properly for you.

**Comment by robert7** [comment]
Yes it works! great!

But I found minor new problem: the welcome dialog on my system now shows centered on other screen then the Quentier app itself. This worked OK before.

What is weird, that the "Shutdown" dialog open centered on Quentier app (=> OK).

![welcome-dlg-screen_20180721_06](https://user-images.githubusercontent.com/1135218/43035174-0d06d208-8ceb-11e8-99d8-68c2c1b47dfa.png)

**Comment by robert7** [comment]
>I wasn't actually able to reproduce the original issue: for me window modality seems to work properly i.e. if I have opened preferences dialog once, I can't do anything with Quentier's main window before I close the dialog i.e.

can't reproduce it now => fine

I don't know how/where I can reopen the issue. Doesn't seem to have that option. I can only fill new issue.
