### ISSUE TITLE
Menu doesn't show

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#190]
Steps to reproduce:

1. Start quentier
2. Close (will close/hide to tray)
3. Select "Show" in tray - main window will show
4. menu can't be displayed anymore
(development version with qt 5.5.1)

![q-menu-screen_20180719_05](https://user-images.githubusercontent.com/1135218/42964350-14714a00-8b97-11e8-9c93-bc17b575ee10.png)

**Comment by d1vanov** [comment]
Ugh, it must be something specific to the window manager used i.e. to DE. I run Plasma 5 and I can't reproduce this myself. Hopefully some workaround should exist (like calling `show` on the menu manually or something like that) but need to google for it.

**Comment by robert7** [comment]
OK.

**Comment by robert7** [comment]
I will investigate later in more detail. I tried to reproduce with Ubuntu 16.04 live CD, but I couldn't. Weird.

**Comment by robert7** [comment]
It can be reproduced easily with [Ubuntu live CD 16.04](https://www.ubuntu.com/download/alternative-downloads) with standard settings with the development version of Quentier from the PPA. Although it works(!) with the same version if started as AppImage.

You can run Ubuntu live CD easily with e.g. [VirtualBox](https://www.virtualbox.org/) on your machine.

As Ubuntu 16.04 with standard settings is fairly common, I think it would be important to fix (but may not be urgent).
[screens-livecd-PPA-version.zip](https://github.com/d1vanov/quentier/files/2213407/screens-livecd-PPA-version.zip)

**Comment by d1vanov** [comment]
I'm curious, have you ever seen this kind of issue with any other Qt app? If yes, it's more likely that it is some Qt issue. Otherwise it's more likely that Quentier does something wrong.

**Comment by robert7** [comment]
>I'm curious, have you ever seen this kind of issue with any other Qt app? 
no. but I have not much experience with Qt (I'm just playing with Qt since ~one month)

**Comment by d1vanov** [comment]
Finally did some googling about this issue - it seems like something special between Qt and Unity: [QTBUG-45067](https://bugreports.qt.io/browse/QTBUG-45067), [QTBUG-58069](https://bugreports.qt.io/browse/QTBUG-58069). The latter one actually contains a hint for the workaround: calling `setNativeMenuBar(false)` on the menu bar. It might be useful to have it as a preference, disabled by default but ready to be enabled in case of issues like that on other platforms as well.

**Comment by robert7** [comment]
OK. Thx.
I also had same with nixnote. But could not reproduce it lately.
To me it seems to be limited to specific Qt version (maybe ~5.5.1).

**Comment by d1vanov** [comment]
This one took much longer than I expected but finally I got the menu to appear within the main window on Ubuntu 16.04 by default. Done in development branch.
