### ISSUE TITLE
Improvements in log verbosity adjustments 

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#196]
After sync failure I would expect at least something to be logged with ERROR level (or at least WARN).
Currently with default INFO level nothing islogged.
Here the point is: for what ever reason sync fails => there should be log with appropriate level.

![screen_20180721_04](https://user-images.githubusercontent.com/1135218/43034965-cfed6570-8ce6-11e8-80e8-fb4a63dbae81.png)

**Comment by robert7** [comment]
here some more data (but the iisu is for logging in anny snyc error - not just this particular
[attachment.zip](https://github.com/d1vanov/quentier/files/2216096/attachment.zip)
again for some reason it tried to create minidump but this itself seems to crash. this could be cause by running the app in debuuger - if I run withut debugger the "dmp" is usually created

**Comment by robert7** [comment]
```2018-07-21 13:18:02.415 CEST libquentier/src/synchronization/SynchronizationManager_p.cpp @ 711 [Debug]: SynchronizationManagerPrivate::onSendLocalChangesFailure: Failed to send new and/or modified saved searches to Evernote service, BAD_DATA_FORMAT exception during the attempt to create a saved search, saved search has no query```

maybe this should be ERROR level - with as much info as possible

**Comment by d1vanov** [comment]
> this could be caused by running the app in debugger

This is exactly the reason why the minidump was not created: Google breakpad by default doesn't create minidump when the app runs under the debugger.

**Comment by robert7** [comment]
>Google breakpad by default doesn't create minidump when the app runs under the debugger.

ok. So for #202 I did already without debugger to reproduce and minidump was created.

**Comment by d1vanov** [comment]
> Failed to send new and/or modified saved searches to Evernote service, BAD_DATA_FORMAT exception during the attempt to create a saved search, saved search has no query

This error was caused by the fact that you created a saved search without specifying any search query into it. Evernote doesn't seem to like it. As a workaround from this error you can edit the saved search to actually specify some search query and try to sync again. What should be done on Quentier side is implementing more strict rules to prevent users from being able to create invalid data items in the first place. And it should be done not only for saved searches but also for notebooks, tags and notes (and probably even note attachments - resources).

**Comment by robert7** [comment]
I renamed the task - the idea is how I described in https://github.com/d1vanov/libquentier/pull/66

Some DEBUGs should become INFO.
Some other very common/verbose DEBUGs should become TRACE.
DEBUG level should not log note contents (this may be blocker for user reporting bugs, as e.g. I don't want to post log with lot of my real notes publicly to github).
Errors/Warnings should be logged with appropriate level (e.g. sync errors)

As we discussed, I will continue with adjustments in this directions..

**Comment by robert7** [comment]
I would like to change the "file - line number" delimiter from "file @ line" to "file:line".
If I run the app in IDE, it makes development easier, as I can click on the filename to go to line.
Although you don't use IDE, it would make life easier for those who do.. 
Is it OK for you?

If don't like the change to be active for all, I could do activated by some command line parameter.
I would also adjust the parsing in log viewer window.

Here example form nixnote:
![screen_20180725_01](https://user-images.githubusercontent.com/1135218/43218798-c018948c-9045-11e8-8105-7ed586a5d6c1.png)

**Comment by d1vanov** [comment]
I don't quite have any strong feelings about the log formatting so ok, let's change it.
