### ISSUE TITLE
With --storageDir parameter set, some files are still written to $HOME/.quentier

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#203]
Not sure if this is intentional - but I see it as bug. Although for most normal user this wouldn't be a problem, for development it would be much helpful, if all files will be written to the directory specified in --storageDir

E.g. I want to run quentier last stable version with my real account in one directory, and the version which I'm currently developing in other directory. I understanded, that this should be possible.
I started like: `./quentier --storageDir /home/rspiegel/.quentier-RS`

So I would expected nothing should be touched in $HOME/.quentier => but it was.
Here is what was written in   $HOME/.quentier:  [home-q.zip](https://github.com/d1vanov/quentier/files/2217148/home-q.zip)
I deleted the directory before.

To reproduce: 
1. move $HOME/.quentier to e.g. $HOME/.quentier-xy
2. start quentier --storageDir $HOME/.quentier-xy

**Comment by robert7** [comment]
FYI I'm going to fix this. The problem is that "applicationPersistentStoragePath()" is called many times before "storageDir" is read in processCommandLineOptions()

**Comment by d1vanov** [comment]
Fixed after merging PR #211 and polishing commit [e9bfbef](https://github.com/d1vanov/quentier/commit/e9bfbeff012e51298f3440221a7174b7cb716ea9) in branch [development](https://github.com/d1vanov/quentier/commit/development).
