### ISSUE TITLE
How to display "All notes"?

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#204]
Could not figure out how to display all notes in all notebooks (this is default view in all Evernote clients). Also all Evernote client have toolbar button "All notes" (which I'm missing in Quentier).

Not sure if this is some design decision/limitation. Could not find answer in wiki.
I would prefer to display list of all notes in all notebooks as default + also have the toolbar button (with keyboard shortcut - Ctrl-Shift-A as it is in Evernote Desktop).

![screen_20180722_03](https://user-images.githubusercontent.com/1135218/43048365-d37d706c-8de6-11e8-8ddb-2c7e8c9558ea.png)

**Comment by d1vanov** [comment]
First option: expand note filters (above the notes list, press on the arrow icon) and remove the notebook from the filter. Second option: right click on the notebook list view and choose "Deselect".

**Comment by robert7** [comment]
>First option: expand note filters (above the notes list, press on the arrow icon) and remove the notebook from the filter. 

this works. thx!

but I could not find "Deselect" pls post screenshot
![screen_20180722_07](https://user-images.githubusercontent.com/1135218/43048819-0a637408-8dee-11e8-88af-4eb3b1aceeba.png)

I would later prefer toolbar icon with kbd short cut (but this is now not critical).

**Comment by d1vanov** [comment]
Implemented a convenient way to drop the current notebook from filter: a new row in the notebooks view.
![all_notebooks](https://user-images.githubusercontent.com/2050562/82790236-6a989180-9e74-11ea-86f3-8bd53a9f5c34.png)
One can just click on that row to view notes without filtering by notebooks. The preference is persisted i.e. if this row was selected before quitting the app, it would be selected on the next launch too.

For now the change is available in development branch only.

**Comment by d1vanov** [comment]
Will do a similar thing for tags in #148. In addition will add filtering by currently selected tag which is currently missing. And probably then will do similar things for saved searches.
