### ISSUE TITLE
Display count of found notes and "search in progress" indicator

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#205]
Someway I have feeling, that Quentier displays/finds much less notes then Evernote client.
Can I somewhere see count of found notes (like in Evernote cliient)? I think this could be important for new users to gain confidence, that new client is working reliably.

Next related problem - it seems that search in Quentier is running "async" - which is OK, but currently I have no indication that search is still running. So it happened I entered search term, 3 notes appeared - I wondered WTF - there must be much more - and then like during one minute some more appeared (not sure if all - as there is no count). So maybe some indication that search is in progress (or maybe some indexing etc.)

![screen_20180722_04](https://user-images.githubusercontent.com/1135218/43048503-04d5de36-8de9-11e8-9098-9e4adb194093.png)

**Comment by d1vanov** [comment]
I added an indicator displaying the count of notes in a similar way as the official Evernote app does: it shows the number of notes conforming to the current filter as well as the total number of notes within the account.
![quentier_notes_count_example](https://user-images.githubusercontent.com/2050562/54331956-30efb800-462d-11e9-8f94-59653608d402.png)
As for the "search in progress" indicator, it shouldn't be needed anymore after the introduction of new note model in #233: filtering should now be performed much faster than it used to be.

Done in development branch.
