### ISSUE TITLE
Quentier About message box: show version of actually used libquentier in addition to version of libquentier used during build

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#208]
About box now shows the version of the libquentier library from the time, when the AboutQuentierWidget was built. Which may be different as the version it is actually running with.

I suggest: adding API function to libquentier like "getVersionInfo()" which will get the version from the binary.

![screen_20180724_18](https://user-images.githubusercontent.com/1135218/43150298-dbad8004-8f69-11e8-9c0b-10f32c5d7ba8.png)

Although for correctly installed binary this should not happen, it may confuse some bug reports. E.g. today I was testing the "performance problem" and I wanted to be sure, the correct updated binary is used...

**Comment by robert7** [comment]
>Technically it's not "wrong": it reads "build info", after all

That also depends on the interpretation: I did read it as "build version of the library" :)

But anyway: let us add the "runtime" version of the library - and also print whole version info at beginning of the log (at Quentier startup - with this is cleat which version produced the log file).

We may only print both versions if they are different.

**Comment by d1vanov** [comment]
Done in master and development versions, here's how "About Quentier" widget looks like now:
![aboutquentier](https://user-images.githubusercontent.com/2050562/44908162-08941200-ad0a-11e8-9bd2-224d9cb91d6e.png)
Also implemented proper output for `--version` command line switch which used to say version info obtaining is not implemented yet. Now its output is as follows:
```
Quentier 0.4.0, build info: master, 9c9ad6ab
Built with Qt 5.11.1, uses Qt 5.11.1
Built with libquentier: libqt5quentier.0.4.0.dylib; version 0.4.0, build info: master, cba4ada, built with Qt 5.11.1; uses QtWebEngine
Uses libquentier: version 0.4.0, build info: master, cba4ada, built with Qt 5.11.1; uses QtWebEngine
```
