### ISSUE TITLE
Error sync stopped -  PERMISSION_DENIED parameter=authenticationToken

### ISSUE THREAD

**Issue by timoc** [d1vanov/quentier#220]
I had to re-authorise by 'adding' another evernote account. This should be prompted.

**Comment by d1vanov** [comment]
Could you please clarify which version of Quentier are you using - master or development - and on which OS? In case of Linux please also clarify whether it is AppImage from GitHub releases page or e.g. a package from a PPA for Ubuntu or something else.

Also, could you please see whether some warning/error/info entry is present in the app's log?

Quentier should actually handle the expiration or lack of auth tokens automatically. If it doesn't then something went wrong.

**Comment by timoc** [comment]
My first impression was that it was related to kwallet. but manual  re-auth seemed to fix it.
```
quentier --version                                                                                                                                                                                                                                                                                
Version information output is not implemented yet but will be shortly :)                    
```

should be the ppa version
```
0.4.0-3~ppa~quentier~201808241647~ubuntu18.04.1
```

```
018-08-25 16:42:06.721 CEST libquentier-WRc4Hw/libquentier-0.4.0/src/synchronization/SynchronizationManager_p.cpp:1495 [Warn]: Unexpectedly missing OAuth token in the keychain: Entry not found
2018-08-25 16:42:06.721 CEST qt5-Wce_Q8/quentier-qt5-0.4.0/src/MainWindow.cpp:1824 [Error]: MainWindow::onSynchronizationManagerFailure: Unexpectedly missing OAuth token in the keychain: Entry not found
2018-08-25 16:42:07.142 CEST qt5-Wce_Q8/quentier-qt5-0.4.0/src/MainWindow.cpp:1824 [Error]: MainWindow::onSynchronizationManagerFailure: caught EDAM user exception: error codeqevercloud::EDAMErrorCode: PERMISSION_DENIED: EDAMUserException: PERMISSION_DENIED parameter=authenticationToken
2018-08-25 16:42:07.143 CEST qt5-Wce_Q8/quentier-qt5-0.4.0/src/MainWindow.cpp:1814 [Info]: MainWindow::onSynchronizationStopped
```

**Comment by d1vanov** [comment]
Ok, thanks for the clarification. Yes, currently Quentier relies on the system keychain (KWallet in your case) to contain the proper data when it's expected. And if the data is not there, it breaks down. You are right, instead the authentication should just be requested from user once again.

**Comment by d1vanov** [comment]
Thanks a lot for reporting it!

**Comment by d1vanov** [comment]
This one should be fixed now in both master and development branches - now in case of failure to retrieve the authentication token or shard id from the system keychain Quentier would fall back to doing OAuth i.e. offering user to enter his password and authenticate the app.
