### ISSUE TITLE
Build for tablet via KDE F-Droid Android delivery pipeline

### ISSUE THREAD

**Issue by timoc** [d1vanov/quentier#226]
KDE has an android continuous delivery pipeline for f-droid the open android package repository, with a container build setup. 
https://www.proli.net/2018/06/22/kde-on-android-ci-cd-sdk/

It would be great to be able to use quentier instead of current android app.

**Comment by d1vanov** [comment]
Thank you for the suggestion but at the moment port of Quentier to Android is out of scope:

1. There are quite many things to do for desktop/laptop already
2. I have exactly zero experience in developing for any mobile platform
3. I don't really believe in any "convergence" solution i.e. in using the same UI for desktop and mobile - they have very different needs (e.g. touch vs mouse). That means that UI for mobile platform would have to be done from scratch, port of existing desktop UI is not feasible. Actually, the note editor is implemented using QtWebKit/QtWebEngine and none of these are available for mobile platforms.

On the bright side - libquentier and QEverCloud (Quentier's dependencies) can be built without OAuth and note editor components which depend on technologies not available on mobile platforms. So anyone actually willing to implement Android app based on QEverCloud and libquentier's functionality should be able to do this. I'd volunteer to help with consulting and/or with changes required for further portability.
