### ISSUE TITLE
Google authentication through evernote fails

### ISSUE THREAD

**Issue by mkrutov** [d1vanov/quentier#239]
I've tried to log in to evernote through google account which uses kerberos authentication, and it failed. 
https://i.imgur.com/MwM0spe.png is the screen I'm presented with when using such authentication method. 

Logs dont' have any useful information unfortunatelly:

`2019-03-20 13:25:41.832 CET libquentier-hTL1nK/libquentier-0.4.0/src/note_editor/SpellChecker_p.cpp @ 361 [Info]: No previously cached dic/aff files seem to actually exist anymore, re-scanning the system for dictionaries
`

is the only line that is logged.

**Comment by d1vanov** [comment]
Hi!

Could you please provide some details: which distro are you using, which version of Quentier ("Help" -> "About Quentier" widget displays version info). Also before attempting authentication please enable trace-level log as described [here](https://github.com/d1vanov/quentier/wiki/Collecting-Quentier-logs-for-troubleshooting).

**Comment by mkrutov** [comment]
Thanks for quick response.

Interestingly enough, despite being reproduced 5 times in a row before, this bug was not reproduced this time. I'll keep the trace-level logging in mind when creating the bug next time in case it would happen again.

Thanks again,
