### ISSUE TITLE
Does not sync last tag removal

### ISSUE THREAD

**Issue by robert7** [d1vanov/quentier#266]
Hi,

Problem description:
if you remove the last tag from a note and sync, the note without any tags should be synchronized to the evernote. In reality only local version, where the tag was removed shows the note without tags. Evernote still stores the tag attached to the note.

Steps to reproduce the problem (or log file)
* create a note with some tag
* sync it and check that in evernote web/client it is tagged appropriately
* remove the tag from the note in NixNote, so the note is without any tags
* sync it and check in evernote web/client. the note is still tagged.

Note: I experience the same problem in Nixnote. I checked the code and also did upgrade to qevercloud v4.0.0. It seems to me, that the problem is in qevercloud, but I'm not sure, therefore I'm opening ticket here, where I can reproduce it.
I can open the issue in the qevercloud repository, if you can confirm, its issue in qevercloud..
Related Nixnote issue: https://github.com/robert7/nixnote2/issues/96

I  seems. when the "tagGuids" attribute of "Note" datatype is set to empty Optional, then it will not be synced to Evernote (expected: tags to be removed from note in Evernote).

**Comment by d1vanov** [comment]
Hi,
thanks for the report, I'll look into it when I have some time for that.

**Comment by d1vanov** [comment]
I was able to reproduce the problem but I am not yet sure what the mitigation should be and where. Will look into it more.

**Comment by d1vanov** [comment]
> I seems. when the "tagGuids" attribute of "Note" datatype is set to empty Optional, then it will not be synced to Evernote (expected: tags to be removed from note in Evernote).

This appears to be correct. I was able to produce a workaround for Quentier by replacing empty Optional with non-empty Optional holding an empty list - in this case last tag's removal works. It would of course be nice to not have to do this but have QEverCloud treat empty Optional containing a list of something as empty list of something but I am not sure it would be a simple thing to do. I'll think about it though.

**Comment by robert7** [comment]
>I was able to produce a workaround for Quentier by replacing empty Optional with non-empty Optional holding an empty list 

OK, I will try this. Thanks for a hint.

**Comment by d1vanov** [comment]
After doing some research I don't think it is a kind of thing which needs to be changed in QEverCloud. Evernote API reference explicitly [specifies](http://dev.evernote.com/doc/reference/NoteStore.html#Fn_NoteStore_updateNote) that when updating a note one must include changed fields (i.e. have them as non-empty Optionals) and not include non-changed fields (i.e. have them as empty Optionals). Empty list of tags is a non-empty Optional and represents a changed field from QEverCloud's perspective then. Empty Optional means the list of tags is not being updated.

Therefore I did some changes on libquentier side to mitigate this effect. At first I'm going to merge them to development to see whether the consequences would have any unwanted side effects.

**Comment by robert7** [comment]
OK. I agree.
thank you!

**Comment by robert7** [comment]
I can confirm, that it works now correctly. Great thanks for the hint!
