### ISSUE TITLE
Use OpenSSL 1.1 on Windows to prevent "Tls initialization failed" error

### ISSUE THREAD

**Issue by Heart1010** [d1vanov/quentier#300]
The new window appears but stays blank/white and I have this in the status line
![image](https://user-images.githubusercontent.com/1481680/71900825-db0d7300-315e-11ea-8306-33dba2805142.png)

Quentier version (fresh start / first time user)
![image](https://user-images.githubusercontent.com/1481680/71900858-eeb8d980-315e-11ea-96b3-3668fede5460.png)

**Comment by d1vanov** [comment]
Hi, if I understand correctly, that's Windows version of Quentier, right? If yes, then please attach the app's logs. The instructions for getting logs are [here](https://github.com/d1vanov/quentier/wiki/Collecting-Quentier-logs-for-troubleshooting). In your case it should be enough to open the log viewer via "Help" -> "View logs" and then something already logged should show up. You can press "Save to file" button to save what got logged into a file and then attach it here.
It could also be useful if you reproduced the issue while having "Trace" log level enabled and then attached the produced log.

By the message in the status line it seems there's some problem with communicating with Evernote. I'll see if I can reproduce it myself but I don't have access to Windows 10 machines, only to Windows 7 ones. It could theoretically be some Windows 10's system security facilities prohibit things for unsigned binaries.

**Comment by d1vanov** [comment]
Also please clarify whether you are using portable version (just an archive with exe and some files, no installer) or the installable version. In the former case you can try the installable version.

**Comment by Heart1010** [comment]
Yes - Win10 is correct. Here is the trace...
[quentier_log.txt](https://github.com/d1vanov/quentier/files/4031211/quentier_log.txt)

**Comment by Heart1010** [comment]
> Also please clarify whether you are using portable version (just an archive with exe and some files, no installer) or the installable version. In the former case you can try the installable version.

Tried both (installer x64 and portable - both the same)

**Comment by d1vanov** [comment]
I was able to reproduce the issue on one of Windows 7 machines I have at hand. It seems Qt 5.13.2 doesn't want to load OpenSSL lib of version 1.0.2 which I put into both portable and installable versions. But it works with OpenSSL 1.1 if it's installed separately.

Until I fix my packaging, you can do the following to work around the problem: install OpenSSL from [this site](https://slproweb.com/products/Win32OpenSSL.html). I guess you use 64 bit Quentier version, so [this package](https://slproweb.com/download/Win64OpenSSL_Light-1_1_1d.exe) should be used for it. For 32 bit [this package](https://slproweb.com/download/Win32OpenSSL-1_1_0L.exe) should be used. Run the installer and when it asks where to copy OpenSSL dlls to, choose "The Windows system directory". Alternatively, you can copy libssl and libcrypto dlls from OpenSSL install location to Quentier install location's bin folder, then it should work,

Please try what I wrote above and let me know if it would work or not.

**Comment by Heart1010** [comment]
...with that two files copied to my Quentier install location's bin folder (portable) it works!!! 👍

**Comment by d1vanov** [comment]
Great, thanks! I'll update packaging scripts to use newer OpenSSL then when I have some time for it.

**Comment by d1vanov** [comment]
Fixed this issue properly, you can download a new package from releases page. There's no update notification mechanism within the app yet, that's what I plan to add in the near future.
