### ISSUE TITLE
Installing quentier from stable ubuntu repository, Could not find the program 'quentier'

### ISSUE THREAD

**Issue by NucleaPeon** [d1vanov/quentier#305]
I followed the steps in the README:

    sudo add-apt-repository ppa:d1vanov/quentier-stable
    sudo apt-get update
    sudo apt-get install quentier-qt5

In my application launcher, I get the message in a popup:

    Could not find the program 'quentier'

In my terminal, I see the following available quentier-like programs:

    quentier_crash_handler
    quentier_minidump_stackwalk  
    quentier.syms.compressed

In this state, I cannot run quentier. Thanks in advance.

**Comment by NucleaPeon** [comment]
I attempted to install it from unstable:

    sudo add-apt-repository ppa:d1vanov/quentier-development
    sudo apt-get update
    sudo apt-get install quentier-qt5

I do get the programs `quentier` and `quentier-0.5.0`, but I get the following error:

    quentier: symbol lookup error: quentier: undefined symbol:
    _ZN8quentier24LocalStorageManagerAsync19onSwitchUserRequestENS_7AccountE6QFlagsINS_19LocalStorageManager13StartupOptionEE5QUuid

**Comment by d1vanov** [comment]
Thanks for reporting this, I screwed up packaging in the stable repository, will fix it shortly.

**Comment by d1vanov** [comment]
Fixed this one.

**Comment by NucleaPeon** [comment]
You're on top of things! Thank you
