### ISSUE TITLE
Quentier cannot start because its database is locked (unstable)

### ISSUE THREAD

**Issue by NucleaPeon** [d1vanov/quentier#307]
When I close quentier unstable and attempt to re-open it, I get an error message about a locked database. Opening my system monitor, I see quentier as still running. This can be reproduced by simply using the close button in the title bar or right clicking in taskbar/dock and going to Close and attempting to re-open.

Workaround is to open system monitor and close quentier manually or use the `kill` command

**Comment by NucleaPeon** [comment]
![Screenshot_20200227_112403](https://user-images.githubusercontent.com/1475151/75479459-6ed81000-5954-11ea-85c4-1cff3f21a9c5.png)

**Comment by d1vanov** [comment]
Most probably in your case Quentier main window's close button does not quit the app but minimizes it to the system tray. Actually, when you close the main window for the very first time after the first installation of Quentier, it should ask you what you prefer this action to do - quit the app or minimize it to the system tray. Further behaviour would depend on the preference you have chosen.
You can change this behavour by going to preferences. Can't provide a screenshot right now, I'm on mobile. Will do it later when I have a chance.

**Comment by NucleaPeon** [comment]
I see the Close to Tray checkbox in preferences, and given what you said, it all makes sense now. I don't recall choosing close to tray on first run or seeing any wizard, I could have accidentally skipped past it. 

If Quentier is running in the tray and I try to launch it from my menu, I would then suggest looking for the running instance and showing that instead, if that's a possible solution.

**Comment by d1vanov** [comment]
There's #97 about supporting interprocess discovery and communication which might be used for what you are suggesting. It is possible in theory but it's not very easy. Maybe it would be done some day.

Ok, I'll close this one as we figured out it was a close to tray preference.
