### ISSUE TITLE
[feature request] add counters to the post sync status bar message 

### ISSUE THREAD

**Issue by timoc** [d1vanov/quentier#368]
**Is your feature request related to a problem? Please describe.**
I would like to be able to see the progress of the sync post-processing.   

**Describe the solution you'd like**
The feature request is to add a counter/countdown of things to be processed to the "downloaded sync chunks, parsing messages...." status bar message.
e.g. "Downloaded [x of X] chunks, processing [x of X] notes etc."

**Describe alternatives you've considered**
same idea, but in the notes list title 
e.g. "Notes: x/y [X to add] 
and similar to side bars titles

**Additional context**

**Comment by d1vanov** [comment]
Thanks, I agree it would be a nice feature to have.
How I envision it: counters for processing the stuff from downloaded sync chunks should be added to [RemoteToLocalSynchronizationManager](https://github.com/d1vanov/libquentier/blob/master/src/synchronization/RemoteToLocalSynchronizationManager.h) in libquentier, it would emit the updates of these counters via signals. Signals would be re-sent to outside code via [SynchronizationManagerPrivate](https://github.com/d1vanov/libquentier/blob/master/src/synchronization/SynchronizationManager_p.h) and [SynchronizationManager](https://github.com/d1vanov/libquentier/blob/master/headers/quentier/synchronization/SynchronizationManager.h). On Quentier's side `MainWindow` would subscribe to this new signal and upon receiving it would compute the total percentage and display it in the status bar message.

**Comment by timoc** [comment]
now getting some kind of feedback:
```
 MainWindow::onSynchronizationManagerFailure: Caught EDAM system exception: error code = EDAMErrorCode::INTERNAL_ERROR: 3ae6308ca28e9190f9b89a33641af5c6
```

**Comment by d1vanov** [comment]
Did you mean to leave this comment in #367?
As I explained [here](https://github.com/d1vanov/quentier/issues/367#issuecomment-808691129), `EDAMErrorCode::INTERNAL_ERROR` means problems on Evernote's end. It's not a thing you can do anything about really rather than just wait and try again.
In this ticket I've implemented the counters you requested but for now they are in unstable version only. You use the stable version, don't you?

**Comment by timoc** [comment]
yes. I can switch to unstable if there is no risk of trashing my notes.

**Comment by d1vanov** [comment]
Right now unstable differs from stable just by these counters presence. So there shouldn't be any risk of trashing your notes, whatever you mean by that.
If you decide to switch PPA from stable to unstable, you'd need to remove Quentier's packages first, then change the PPA and then install again. Similarly for going back from unstable to stable. However, you don't really have to switch the PPA just to try out these counters, you can just take [the unstable AppImage](https://github.com/d1vanov/quentier/releases/download/continuous-development/Quentier-development-x86_64.AppImage) and run it once for the sake of testing. And then continue using the stable version from the PPA.

**Comment by timoc** [comment]
is there a change to the SQL schemea? i ran the appimage and it generated this error:
 
```
../src/local_storage/LocalStorageManager_p.cpp:15162 [Error] [local_storage]: can't list objects from the local storage database by filter, last query = SELECT * FROM Notes LEFT OUTER JOIN SharedNotes ON ((Notes.guid IS NOT NULL) AND (Notes.guid = SharedNotes.sharedNoteNoteGuid)) LEFT OUTER JOIN NoteRestrictions ON Notes.localUid = NoteRestrictions.noteLocalUid LEFT OUTER JOIN NoteLimits ON Notes.localUid = NoteLimits.noteLocalUid ORDER BY modificationTimestamp ASC LIMIT 10 OFFSET 680, last error = QSqlError(13, Unable to fetch row, database or disk is full)
../src/local_storage/LocalStorageManager_p.cpp:2963 [Warn] [local_storage]: Can't list notes from the local storage database, can't list objects from the local storage database by filter: database or disk is full Unable to fetch row
../src/local_storage/LocalStorageManager_p.cpp:4801 [Error] [local_storage]: Can't end the SQL transaction: QSqlError(1, Unable to fetch row, cannot commit - no transaction is active)
```

**Comment by d1vanov** [comment]
There were no changes to the schema, it has been stable for several years. The error says "database or disk is full". Isn't your hard drive full by any chance? If not then it might be some quirk of AppImage version of Quentier. I don't see such error on my system though with the same AppImage.
If this is a consistent problem for you, I could probably merge the counters to the stable version, it seems this change is harmless.

**Comment by timoc** [comment]
I cleared the database and started again, have not seen it since.

**Comment by timoc** [comment]
Seems to work ok, so closing.
