### ISSUE TITLE
[Bug] synchronization overrides changes made to the note locally

### ISSUE THREAD

**Issue by ra3ggi** [d1vanov/quentier#379]
Sequence of actions:
1. Doing a search on the Note (ctrl+F).
2. Without closing the search window - make changes in the note.
3. Close the Search window on the note.
4. Do synchronization (F9).
Result - changes in note were not sent to server.
The unstable version is used, which was installed from the repository.

**Comment by ra3ggi** [comment]
Sorry, but the error has stopped playing.
Perhaps the problem is with me and not with the program :)

**Comment by d1vanov** [comment]
I'll take a look into it a bit later but it might be that changes you did to the note were not saved before the sync was started. They should have been but maybe somehow it didn't happen.

You can save the note manually before launching the sync, the default shortcut is Ctrl + S or you can press the corresponding button in the editor bar. The button would be active when the changes to the note are not yet saved. If it's inactive it means the note is already saved.

**Comment by ra3ggi** [comment]
Is it possible to set up a synchronization when the program starts and synchronization when the program closes?

**Comment by d1vanov** [comment]
Right now there's no such option. I might add such an option in future.

**Comment by d1vanov** [comment]
Tried to reproduce the issue but no luck, for me the note saved automatically before launching the sync.

If the problem reproduces in future, please try to collect debug or trace logs when it happens. It is explained in the [wiki article](https://github.com/d1vanov/quentier/wiki/Collecting-Quentier-logs-for-troubleshooting) how to do it. There is a small possibility that the process of saving the note was unsuccessful for some reason but such event should have been logged.
