### ISSUE TITLE
[feature request] Automatic sync on startup

### ISSUE THREAD

**Issue by d1vanov** [d1vanov/quentier#387]
If Quentier is opened with Evernote account, it would be useful to add an option to sync automatically right on startup, to prevent the opportunity for conflicts when someone forgets to sync and edits a note which was changed via some other Evernote client.

**Comment by ra3ggi** [comment]
It is necessary to make somehow a notification (indication) that the synchronization at startup was carried out or ended with an error (in the status bar).
When closing the program it is enough to make a message in case of error. 
It would be nice if it was configured in the "Settings" - who does not need it, he will turn off the message.

**Comment by d1vanov** [comment]
Merged a new option to run sync on startup into the unstable version.

By default it is switched off, if you want to use it, you need to switch it on via "Edit" -> "Preferences" -> "Synchronization" tab -> check "Run sync on startup". The preference is persisted per account i.e. if you have multiple accounts, you would have to enable it for every account you use, for each account it would be off by default.
