### ISSUE TITLE
[bug] cannot login: "Can't authenticate to Evernote: SSL Errors: The peer did not present any certificate"

### ISSUE THREAD

**Issue by vitaly-zdanevich** [d1vanov/quentier#418]
![image](https://github.com/d1vanov/quentier/assets/3514015/0b09205d-e0e2-4992-8a58-07675cd22e9a)

The latest appImage:
![image](https://github.com/d1vanov/quentier/assets/3514015/1d450c80-e1af-4e9b-aebc-55032e04d3b4)

Gentoo Linux, no-multilib profile.

**Comment by d1vanov** [comment]
I don't think I can solve this, it appears to be a limitation of AppImage format: AppImages don't bundle OpenSSL library but depend on the version of it from the host system. So any incompatibilities between OpenSSL libs on the host on which AppImage was built and on the host on which the AppImage is attempted to run result in errors.

Similar errors related to other low-level libs can also be encountered with AppImages and not much can be done about it.

I'd advise against using an AppImage version of Quentier, at least not for long term. I provide native packages for a lot of distros. Unfortunately not for Gentoo though.

**Comment by d1vanov** [comment]
If you wish, you can try to install the legacy OpenSSL 1.1 on your system and see if it makes any difference for the AppImage. The AppImage version of Quentier is built on Ubuntu 20.04 which ships with OpenSSL 1.1 while most more modern distros have migrated to OpenSSL 3.x, it is likely the source of incompatibilities.

**Comment by vitaly-zdanevich** [comment]
> Quentier is built on Ubuntu 20.04

Maybe if you build on Ubuntu 22 or 24 it will be solved?

Installing of old SSL can be bad for security?

**Comment by d1vanov** [comment]
AppImage project recommends using the oldest still supported Ubuntu LTS version which is 20.04 at the moment.

Old OpenSSL is certainly not very good for security but depending on how particular distros implement versioning, you might be able to install it in such a way that it's only used by "legacy" apps which require it. I don't really know how Gentoo handles it though.
